server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: password
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/microservice-basic
    username: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  application:
    name: Department-Service
  zipkin:
    base-url: http://127.0.0.1:9411/
